# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'svn_update.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 800)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(50, 210, 1041, 471))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.modifyListWidget = QtWidgets.QListWidget(self.layoutWidget)
        self.modifyListWidget.setObjectName("modifyListWidget")
        self.verticalLayout_2.addWidget(self.modifyListWidget)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.addListWidget = QtWidgets.QListWidget(self.layoutWidget)
        self.addListWidget.setObjectName("addListWidget")
        self.verticalLayout_3.addWidget(self.addListWidget)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)
        self.deleteListWidget = QtWidgets.QListWidget(self.layoutWidget)
        self.deleteListWidget.setObjectName("deleteListWidget")
        self.verticalLayout_4.addWidget(self.deleteListWidget)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(273, 21, 591, 131))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.pathLineEdit = QtWidgets.QLineEdit(self.widget)
        self.pathLineEdit.setObjectName("pathLineEdit")
        self.horizontalLayout_4.addWidget(self.pathLineEdit)
        self.opendirPushButton = QtWidgets.QPushButton(self.widget)
        self.opendirPushButton.setMaximumSize(QtCore.QSize(300, 16777215))
        self.opendirPushButton.setObjectName("opendirPushButton")
        self.horizontalLayout_4.addWidget(self.opendirPushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.oldversionLineEdit = QtWidgets.QLineEdit(self.widget)
        self.oldversionLineEdit.setMaximumSize(QtCore.QSize(150, 16777215))
        self.oldversionLineEdit.setObjectName("oldversionLineEdit")
        self.horizontalLayout_2.addWidget(self.oldversionLineEdit)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.newversionLineEdit = QtWidgets.QLineEdit(self.widget)
        self.newversionLineEdit.setMaximumSize(QtCore.QSize(150, 16777215))
        self.newversionLineEdit.setObjectName("newversionLineEdit")
        self.horizontalLayout_2.addWidget(self.newversionLineEdit)
        self.startPushButton = QtWidgets.QPushButton(self.widget)
        self.startPushButton.setObjectName("startPushButton")
        self.horizontalLayout_2.addWidget(self.startPushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.outputLineEdit = QtWidgets.QLineEdit(self.widget)
        self.outputLineEdit.setText("")
        self.outputLineEdit.setObjectName("outputLineEdit")
        self.horizontalLayout.addWidget(self.outputLineEdit)
        self.outputPushButton = QtWidgets.QPushButton(self.widget)
        self.outputPushButton.setObjectName("outputPushButton")
        self.horizontalLayout.addWidget(self.outputPushButton)
        self.copyPushButton = QtWidgets.QPushButton(self.widget)
        self.copyPushButton.setEnabled(False)
        self.copyPushButton.setObjectName("copyPushButton")
        self.horizontalLayout.addWidget(self.copyPushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "版本更新差异"))
        self.label_4.setText(_translate("MainWindow", "修改项"))
        self.label_5.setText(_translate("MainWindow", "新增项"))
        self.label_6.setText(_translate("MainWindow", "删除项"))
        self.label.setText(_translate("MainWindow", "本地SVN目录"))
        self.opendirPushButton.setText(_translate("MainWindow", "选择"))
        self.label_2.setText(_translate("MainWindow", "历史版本号"))
        self.label_3.setText(_translate("MainWindow", "最新版本号"))
        self.startPushButton.setText(_translate("MainWindow", "开始查询"))
        self.label_7.setText(_translate("MainWindow", "输出目录"))
        self.outputPushButton.setText(_translate("MainWindow", "选择"))
        self.copyPushButton.setText(_translate("MainWindow", "开始拷贝"))

