# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'svn_update.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 704)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(50, 210, 1041, 197))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.modifyTextEdit = QtWidgets.QTextEdit(self.layoutWidget)
        self.modifyTextEdit.setObjectName("modifyTextEdit")
        self.verticalLayout_2.addWidget(self.modifyTextEdit)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.addTextEdit = QtWidgets.QTextEdit(self.layoutWidget)
        self.addTextEdit.setObjectName("addTextEdit")
        self.verticalLayout_3.addWidget(self.addTextEdit)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)
        self.deleteTextEdit = QtWidgets.QTextEdit(self.layoutWidget)
        self.deleteTextEdit.setObjectName("deleteTextEdit")
        self.verticalLayout_4.addWidget(self.deleteTextEdit)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(273, 21, 591, 131))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.pathLineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.pathLineEdit.setObjectName("pathLineEdit")
        self.horizontalLayout_4.addWidget(self.pathLineEdit)
        self.opendirPushButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.opendirPushButton.setMaximumSize(QtCore.QSize(300, 16777215))
        self.opendirPushButton.setObjectName("opendirPushButton")
        self.horizontalLayout_4.addWidget(self.opendirPushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.oldversionLineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.oldversionLineEdit.setMaximumSize(QtCore.QSize(150, 16777215))
        self.oldversionLineEdit.setObjectName("oldversionLineEdit")
        self.horizontalLayout_2.addWidget(self.oldversionLineEdit)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_3.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.newversionLineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.newversionLineEdit.setMaximumSize(QtCore.QSize(150, 16777215))
        self.newversionLineEdit.setObjectName("newversionLineEdit")
        self.horizontalLayout_2.addWidget(self.newversionLineEdit)
        self.startPushButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.startPushButton.setObjectName("startPushButton")
        self.horizontalLayout_2.addWidget(self.startPushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.outputLineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.outputLineEdit.setText("")
        self.outputLineEdit.setObjectName("outputLineEdit")
        self.horizontalLayout.addWidget(self.outputLineEdit)
        self.outputPushButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.outputPushButton.setObjectName("outputPushButton")
        self.horizontalLayout.addWidget(self.outputPushButton)
        self.copyPushButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.copyPushButton.setEnabled(False)
        self.copyPushButton.setObjectName("copyPushButton")
        self.horizontalLayout.addWidget(self.copyPushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.checkPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.checkPushButton.setGeometry(QtCore.QRect(500, 580, 161, 32))
        self.checkPushButton.setObjectName("checkPushButton")
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(290, 440, 571, 91))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_5.addWidget(self.label_8)
        self.oldLineEdit = QtWidgets.QLineEdit(self.layoutWidget2)
        self.oldLineEdit.setObjectName("oldLineEdit")
        self.horizontalLayout_5.addWidget(self.oldLineEdit)
        self.oldPushButton = QtWidgets.QPushButton(self.layoutWidget2)
        self.oldPushButton.setObjectName("oldPushButton")
        self.horizontalLayout_5.addWidget(self.oldPushButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_6.addWidget(self.label_9)
        self.newLineEdit = QtWidgets.QLineEdit(self.layoutWidget2)
        self.newLineEdit.setObjectName("newLineEdit")
        self.horizontalLayout_6.addWidget(self.newLineEdit)
        self.newPushButton = QtWidgets.QPushButton(self.layoutWidget2)
        self.newPushButton.setObjectName("newPushButton")
        self.horizontalLayout_6.addWidget(self.newPushButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.layoutWidget3 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget3.setGeometry(QtCore.QRect(460, 620, 240, 23))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_7.addWidget(self.label_10)
        self.sizeLineEdit = QtWidgets.QLineEdit(self.layoutWidget3)
        self.sizeLineEdit.setObjectName("sizeLineEdit")
        self.horizontalLayout_7.addWidget(self.sizeLineEdit)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_7.addWidget(self.label_11)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "版本更新差异"))
        self.label_4.setText(_translate("MainWindow", "修改项"))
        self.label_5.setText(_translate("MainWindow", "新增项"))
        self.label_6.setText(_translate("MainWindow", "删除项"))
        self.label.setText(_translate("MainWindow", "本地SVN目录"))
        self.opendirPushButton.setText(_translate("MainWindow", "选择"))
        self.label_2.setText(_translate("MainWindow", "历史版本号"))
        self.label_3.setText(_translate("MainWindow", "最新版本号"))
        self.startPushButton.setText(_translate("MainWindow", "开始查询"))
        self.label_7.setText(_translate("MainWindow", "输出目录"))
        self.outputPushButton.setText(_translate("MainWindow", "选择"))
        self.copyPushButton.setText(_translate("MainWindow", "开始拷贝"))
        self.checkPushButton.setText(_translate("MainWindow", "开始检查"))
        self.label_8.setText(_translate("MainWindow", "旧版本压缩包"))
        self.oldPushButton.setText(_translate("MainWindow", "选择"))
        self.label_9.setText(_translate("MainWindow", "新版本压缩包"))
        self.newPushButton.setText(_translate("MainWindow", "选择"))
        self.label_10.setText(_translate("MainWindow", "热更新包大小"))
        self.label_11.setText(_translate("MainWindow", "KB"))

