# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'activity.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_gmtools(object):
    def setupUi(self, gmtools):
        gmtools.setObjectName("gmtools")
        gmtools.resize(1200, 800)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../Desktop/IMG_0114.PNG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        gmtools.setWindowIcon(icon)
        gmtools.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(gmtools)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(30, 60, 1141, 711))
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.nameListWidget = QtWidgets.QListWidget(self.tab)
        self.nameListWidget.setGeometry(QtCore.QRect(50, 90, 431, 91))
        self.nameListWidget.setObjectName("nameListWidget")
        self.layoutWidget = QtWidgets.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(50, 200, 431, 61))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.timeLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.timeLineEdit.setObjectName("timeLineEdit")
        self.horizontalLayout_2.addWidget(self.timeLineEdit)
        self.layoutWidget1 = QtWidgets.QWidget(self.tab)
        self.layoutWidget1.setGeometry(QtCore.QRect(50, 280, 1021, 201))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.msgTableWidget = QtWidgets.QTableWidget(self.layoutWidget1)
        self.msgTableWidget.setObjectName("msgTableWidget")
        self.msgTableWidget.setColumnCount(5)
        self.msgTableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.msgTableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.msgTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.msgTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.msgTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.msgTableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.msgTableWidget.setHorizontalHeaderItem(4, item)
        self.msgTableWidget.horizontalHeader().setDefaultSectionSize(80)
        self.verticalLayout_2.addWidget(self.msgTableWidget)
        self.msg_TableWidget = QtWidgets.QTableWidget(self.layoutWidget1)
        self.msg_TableWidget.setObjectName("msg_TableWidget")
        self.msg_TableWidget.setColumnCount(4)
        self.msg_TableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.msg_TableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.msg_TableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.msg_TableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.msg_TableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.msg_TableWidget.setHorizontalHeaderItem(3, item)
        self.msg_TableWidget.horizontalHeader().setDefaultSectionSize(250)
        self.verticalLayout_2.addWidget(self.msg_TableWidget)
        self.layoutWidget2 = QtWidgets.QWidget(self.tab)
        self.layoutWidget2.setGeometry(QtCore.QRect(50, 30, 431, 25))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.nameLineEdit = QtWidgets.QLineEdit(self.layoutWidget2)
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.horizontalLayout.addWidget(self.nameLineEdit)
        self.horizontalLayout_25.addLayout(self.horizontalLayout)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.headingRadioButton = QtWidgets.QRadioButton(self.layoutWidget2)
        self.headingRadioButton.setChecked(True)
        self.headingRadioButton.setObjectName("headingRadioButton")
        self.horizontalLayout_24.addWidget(self.headingRadioButton)
        self.commentRadioButton = QtWidgets.QRadioButton(self.layoutWidget2)
        self.commentRadioButton.setObjectName("commentRadioButton")
        self.horizontalLayout_24.addWidget(self.commentRadioButton)
        self.horizontalLayout_25.addLayout(self.horizontalLayout_24)
        self.mallTableWidget = QtWidgets.QTableWidget(self.tab)
        self.mallTableWidget.setEnabled(True)
        self.mallTableWidget.setGeometry(QtCore.QRect(51, 518, 1019, 151))
        self.mallTableWidget.setShowGrid(True)
        self.mallTableWidget.setObjectName("mallTableWidget")
        self.mallTableWidget.setColumnCount(9)
        self.mallTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.mallTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.mallTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.mallTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.mallTableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.mallTableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.mallTableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.mallTableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.mallTableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.mallTableWidget.setHorizontalHeaderItem(8, item)
        self.rewardTableWidget = QtWidgets.QTableWidget(self.tab)
        self.rewardTableWidget.setGeometry(QtCore.QRect(51, 518, 1019, 151))
        self.rewardTableWidget.setObjectName("rewardTableWidget")
        self.rewardTableWidget.setColumnCount(5)
        self.rewardTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.rewardTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.rewardTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.rewardTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.rewardTableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.rewardTableWidget.setHorizontalHeaderItem(4, item)
        self.rewardTableWidget.horizontalHeader().setDefaultSectionSize(200)
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(51, 491, 56, 19))
        self.label_5.setObjectName("label_5")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.goodsListWidget = QtWidgets.QListWidget(self.tab_2)
        self.goodsListWidget.setGeometry(QtCore.QRect(60, 100, 411, 111))
        self.goodsListWidget.setObjectName("goodsListWidget")
        self.goods_TableWidget = QtWidgets.QTableWidget(self.tab_2)
        self.goods_TableWidget.setGeometry(QtCore.QRect(60, 260, 1011, 161))
        self.goods_TableWidget.setObjectName("goods_TableWidget")
        self.goods_TableWidget.setColumnCount(7)
        self.goods_TableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.goods_TableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.goods_TableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.goods_TableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.goods_TableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.goods_TableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.goods_TableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.goods_TableWidget.setHorizontalHeaderItem(6, item)
        self.goods_TableWidget.horizontalHeader().setDefaultSectionSize(200)
        self.goodsTableWidget = QtWidgets.QTableWidget(self.tab_2)
        self.goodsTableWidget.setGeometry(QtCore.QRect(60, 260, 521, 411))
        self.goodsTableWidget.setObjectName("goodsTableWidget")
        self.goodsTableWidget.setColumnCount(2)
        self.goodsTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.goodsTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.goodsTableWidget.setHorizontalHeaderItem(1, item)
        self.goodsTableWidget.horizontalHeader().setDefaultSectionSize(300)
        self.annTableWidget = QtWidgets.QTableWidget(self.tab_2)
        self.annTableWidget.setGeometry(QtCore.QRect(60, 480, 1011, 192))
        self.annTableWidget.setObjectName("annTableWidget")
        self.annTableWidget.setColumnCount(3)
        self.annTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.annTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.annTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.annTableWidget.setHorizontalHeaderItem(2, item)
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(60, 230, 60, 16))
        self.label_6.setObjectName("label_6")
        self.label_15 = QtWidgets.QLabel(self.tab_2)
        self.label_15.setGeometry(QtCore.QRect(60, 450, 60, 16))
        self.label_15.setObjectName("label_15")
        self.widget = QtWidgets.QWidget(self.tab_2)
        self.widget.setGeometry(QtCore.QRect(61, 45, 347, 27))
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.goodsLineEdit = QtWidgets.QLineEdit(self.widget)
        self.goodsLineEdit.setObjectName("goodsLineEdit")
        self.horizontalLayout_3.addWidget(self.goodsLineEdit)
        self.goodsRadioButton = QtWidgets.QRadioButton(self.widget)
        self.goodsRadioButton.setChecked(True)
        self.goodsRadioButton.setObjectName("goodsRadioButton")
        self.horizontalLayout_3.addWidget(self.goodsRadioButton)
        self.radioButton_3 = QtWidgets.QRadioButton(self.widget)
        self.radioButton_3.setObjectName("radioButton_3")
        self.horizontalLayout_3.addWidget(self.radioButton_3)
        self.dropRadioButton = QtWidgets.QRadioButton(self.widget)
        self.dropRadioButton.setObjectName("dropRadioButton")
        self.horizontalLayout_3.addWidget(self.dropRadioButton)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.frame = QtWidgets.QFrame(self.tab_4)
        self.frame.setGeometry(QtCore.QRect(550, 390, 521, 251))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.layoutWidget3 = QtWidgets.QWidget(self.frame)
        self.layoutWidget3.setGeometry(QtCore.QRect(20, 20, 481, 211))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_16 = QtWidgets.QLabel(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_17.addWidget(self.label_16)
        self.radioButton = QtWidgets.QRadioButton(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton.sizePolicy().hasHeightForWidth())
        self.radioButton.setSizePolicy(sizePolicy)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_17.addWidget(self.radioButton)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.allserverRadioButton = QtWidgets.QRadioButton(self.layoutWidget3)
        self.allserverRadioButton.setObjectName("allserverRadioButton")
        self.horizontalLayout_16.addWidget(self.allserverRadioButton)
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_16.addWidget(self.pushButton)
        self.horizontalLayout_17.addLayout(self.horizontalLayout_16)
        self.verticalLayout_6.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_18 = QtWidgets.QLabel(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_19.addWidget(self.label_18)
        self.titleLineEdit = QtWidgets.QLineEdit(self.layoutWidget3)
        self.titleLineEdit.setObjectName("titleLineEdit")
        self.horizontalLayout_19.addWidget(self.titleLineEdit)
        self.verticalLayout_6.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_19 = QtWidgets.QLabel(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_20.addWidget(self.label_19)
        self.commentLineEdit = QtWidgets.QLineEdit(self.layoutWidget3)
        self.commentLineEdit.setObjectName("commentLineEdit")
        self.horizontalLayout_20.addWidget(self.commentLineEdit)
        self.verticalLayout_6.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_20 = QtWidgets.QLabel(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_21.addWidget(self.label_20)
        self.itemlistLineEdit = QtWidgets.QLineEdit(self.layoutWidget3)
        self.itemlistLineEdit.setObjectName("itemlistLineEdit")
        self.horizontalLayout_21.addWidget(self.itemlistLineEdit)
        self.verticalLayout_6.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_21 = QtWidgets.QLabel(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_22.addWidget(self.label_21)
        self.dayLineEdit = QtWidgets.QLineEdit(self.layoutWidget3)
        self.dayLineEdit.setObjectName("dayLineEdit")
        self.horizontalLayout_22.addWidget(self.dayLineEdit)
        self.label_22 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_22.addWidget(self.label_22)
        self.secondLineEdit = QtWidgets.QLineEdit(self.layoutWidget3)
        self.secondLineEdit.setObjectName("secondLineEdit")
        self.horizontalLayout_22.addWidget(self.secondLineEdit)
        self.label_23 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_22.addWidget(self.label_23)
        self.verticalLayout_6.addLayout(self.horizontalLayout_22)
        self.frame_2 = QtWidgets.QFrame(self.tab_4)
        self.frame_2.setGeometry(QtCore.QRect(20, 390, 511, 251))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.layoutWidget4 = QtWidgets.QWidget(self.frame_2)
        self.layoutWidget4.setGeometry(QtCore.QRect(20, 20, 471, 211))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_13 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_9.addWidget(self.label_13)
        self.otherComboBox = QtWidgets.QComboBox(self.layoutWidget4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.otherComboBox.sizePolicy().hasHeightForWidth())
        self.otherComboBox.setSizePolicy(sizePolicy)
        self.otherComboBox.setEditable(True)
        self.otherComboBox.setObjectName("otherComboBox")
        self.horizontalLayout_9.addWidget(self.otherComboBox)
        self.executePushButton = QtWidgets.QPushButton(self.layoutWidget4)
        self.executePushButton.setObjectName("executePushButton")
        self.horizontalLayout_9.addWidget(self.executePushButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_25 = QtWidgets.QLabel(self.layoutWidget4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_26.addWidget(self.label_25)
        self.comboBox_2 = QtWidgets.QComboBox(self.layoutWidget4)
        self.comboBox_2.setObjectName("comboBox_2")
        self.horizontalLayout_26.addWidget(self.comboBox_2)
        self.selfPushButton = QtWidgets.QPushButton(self.layoutWidget4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selfPushButton.sizePolicy().hasHeightForWidth())
        self.selfPushButton.setSizePolicy(sizePolicy)
        self.selfPushButton.setObjectName("selfPushButton")
        self.horizontalLayout_26.addWidget(self.selfPushButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_26)
        self.textEdit_2 = QtWidgets.QTextEdit(self.tab_4)
        self.textEdit_2.setGeometry(QtCore.QRect(920, 50, 201, 251))
        self.textEdit_2.setObjectName("textEdit_2")
        self.frame_3 = QtWidgets.QFrame(self.tab_4)
        self.frame_3.setGeometry(QtCore.QRect(30, 20, 461, 351))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.layoutWidget5 = QtWidgets.QWidget(self.frame_3)
        self.layoutWidget5.setGeometry(QtCore.QRect(20, 20, 421, 301))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget5)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_5.addWidget(self.label_8)
        self.nickLineEdit = QtWidgets.QLineEdit(self.layoutWidget5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nickLineEdit.sizePolicy().hasHeightForWidth())
        self.nickLineEdit.setSizePolicy(sizePolicy)
        self.nickLineEdit.setObjectName("nickLineEdit")
        self.horizontalLayout_5.addWidget(self.nickLineEdit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.nickListWidget = QtWidgets.QListWidget(self.layoutWidget5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nickListWidget.sizePolicy().hasHeightForWidth())
        self.nickListWidget.setSizePolicy(sizePolicy)
        self.nickListWidget.setObjectName("nickListWidget")
        self.verticalLayout_3.addWidget(self.nickListWidget)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_24 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_27.addWidget(self.label_24)
        self.clearPushButton = QtWidgets.QPushButton(self.layoutWidget5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clearPushButton.sizePolicy().hasHeightForWidth())
        self.clearPushButton.setSizePolicy(sizePolicy)
        self.clearPushButton.setObjectName("clearPushButton")
        self.horizontalLayout_27.addWidget(self.clearPushButton)
        self.verticalLayout_8.addLayout(self.horizontalLayout_27)
        self.nicklistListWidget = QtWidgets.QListWidget(self.layoutWidget5)
        self.nicklistListWidget.setObjectName("nicklistListWidget")
        self.verticalLayout_8.addWidget(self.nicklistListWidget)
        self.verticalLayout.addLayout(self.verticalLayout_8)
        self.frame_4 = QtWidgets.QFrame(self.tab_4)
        self.frame_4.setGeometry(QtCore.QRect(510, 20, 361, 351))
        self.frame_4.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.layoutWidget6 = QtWidgets.QWidget(self.frame_4)
        self.layoutWidget6.setGeometry(QtCore.QRect(20, 20, 311, 301))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.layoutWidget6)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.goodsLineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget6)
        self.goodsLineEdit_2.setObjectName("goodsLineEdit_2")
        self.horizontalLayout_15.addWidget(self.goodsLineEdit_2)
        self.nameRadioButton = QtWidgets.QRadioButton(self.layoutWidget6)
        self.nameRadioButton.setChecked(True)
        self.nameRadioButton.setObjectName("nameRadioButton")
        self.horizontalLayout_15.addWidget(self.nameRadioButton)
        self.idRadioButton = QtWidgets.QRadioButton(self.layoutWidget6)
        self.idRadioButton.setObjectName("idRadioButton")
        self.horizontalLayout_15.addWidget(self.idRadioButton)
        self.verticalLayout_7.addLayout(self.horizontalLayout_15)
        self.goodsListWidget_2 = QtWidgets.QListWidget(self.layoutWidget6)
        self.goodsListWidget_2.setObjectName("goodsListWidget_2")
        self.verticalLayout_7.addWidget(self.goodsListWidget_2)
        self.verticalLayout_10.addLayout(self.verticalLayout_7)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_26 = QtWidgets.QLabel(self.layoutWidget6)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_28.addWidget(self.label_26)
        self.clearPushButton_2 = QtWidgets.QPushButton(self.layoutWidget6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clearPushButton_2.sizePolicy().hasHeightForWidth())
        self.clearPushButton_2.setSizePolicy(sizePolicy)
        self.clearPushButton_2.setObjectName("clearPushButton_2")
        self.horizontalLayout_28.addWidget(self.clearPushButton_2)
        self.verticalLayout_9.addLayout(self.horizontalLayout_28)
        self.nicklistListWidget_2 = QtWidgets.QListWidget(self.layoutWidget6)
        self.nicklistListWidget_2.setObjectName("nicklistListWidget_2")
        self.verticalLayout_9.addWidget(self.nicklistListWidget_2)
        self.verticalLayout_10.addLayout(self.verticalLayout_9)
        self.verticalLayout_12.addLayout(self.verticalLayout_10)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_12 = QtWidgets.QLabel(self.layoutWidget6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_6.addWidget(self.label_12)
        self.countLineEdit = QtWidgets.QLineEdit(self.layoutWidget6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.countLineEdit.sizePolicy().hasHeightForWidth())
        self.countLineEdit.setSizePolicy(sizePolicy)
        self.countLineEdit.setObjectName("countLineEdit")
        self.horizontalLayout_6.addWidget(self.countLineEdit)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_6)
        self.sendPushButton = QtWidgets.QPushButton(self.layoutWidget6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sendPushButton.sizePolicy().hasHeightForWidth())
        self.sendPushButton.setSizePolicy(sizePolicy)
        self.sendPushButton.setObjectName("sendPushButton")
        self.horizontalLayout_8.addWidget(self.sendPushButton)
        self.addmailPushButton = QtWidgets.QPushButton(self.layoutWidget6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addmailPushButton.sizePolicy().hasHeightForWidth())
        self.addmailPushButton.setSizePolicy(sizePolicy)
        self.addmailPushButton.setObjectName("addmailPushButton")
        self.horizontalLayout_8.addWidget(self.addmailPushButton)
        self.verticalLayout_12.addLayout(self.horizontalLayout_8)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.frame_5 = QtWidgets.QFrame(self.tab_5)
        self.frame_5.setGeometry(QtCore.QRect(230, 40, 671, 371))
        self.frame_5.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.layoutWidget7 = QtWidgets.QWidget(self.frame_5)
        self.layoutWidget7.setGeometry(QtCore.QRect(100, 20, 471, 321))
        self.layoutWidget7.setObjectName("layoutWidget7")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.layoutWidget7)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_17 = QtWidgets.QLabel(self.layoutWidget7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_23.addWidget(self.label_17)
        self.sqlComboBox = QtWidgets.QComboBox(self.layoutWidget7)
        self.sqlComboBox.setObjectName("sqlComboBox")
        self.horizontalLayout_23.addWidget(self.sqlComboBox)
        self.verticalLayout_11.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.tsRadioButton = QtWidgets.QRadioButton(self.layoutWidget7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tsRadioButton.sizePolicy().hasHeightForWidth())
        self.tsRadioButton.setSizePolicy(sizePolicy)
        self.tsRadioButton.setChecked(True)
        self.tsRadioButton.setObjectName("tsRadioButton")
        self.horizontalLayout_10.addWidget(self.tsRadioButton)
        self.tuRadioButton = QtWidgets.QRadioButton(self.layoutWidget7)
        self.tuRadioButton.setObjectName("tuRadioButton")
        self.horizontalLayout_10.addWidget(self.tuRadioButton)
        self.verticalLayout_11.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.sqlTextEdit = QtWidgets.QTextEdit(self.layoutWidget7)
        self.sqlTextEdit.setObjectName("sqlTextEdit")
        self.horizontalLayout_18.addWidget(self.sqlTextEdit)
        self.sqlPushButton = QtWidgets.QPushButton(self.layoutWidget7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sqlPushButton.sizePolicy().hasHeightForWidth())
        self.sqlPushButton.setSizePolicy(sizePolicy)
        self.sqlPushButton.setObjectName("sqlPushButton")
        self.horizontalLayout_18.addWidget(self.sqlPushButton)
        self.verticalLayout_11.addLayout(self.horizontalLayout_18)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_11.addWidget(self.label_11)
        self.resultTextEdit = QtWidgets.QTextEdit(self.layoutWidget7)
        self.resultTextEdit.setObjectName("resultTextEdit")
        self.verticalLayout_11.addWidget(self.resultTextEdit)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.layoutWidget8 = QtWidgets.QWidget(self.tab_3)
        self.layoutWidget8.setGeometry(QtCore.QRect(270, 50, 551, 391))
        self.layoutWidget8.setObjectName("layoutWidget8")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget8)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget8)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_11.addWidget(self.label_7)
        self.tableLineEdit = QtWidgets.QLineEdit(self.layoutWidget8)
        self.tableLineEdit.setObjectName("tableLineEdit")
        self.horizontalLayout_11.addWidget(self.tableLineEdit)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_14 = QtWidgets.QLabel(self.layoutWidget8)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_12.addWidget(self.label_14)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget8)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_12.addWidget(self.lineEdit)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_12)
        self.verticalLayout_5.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.tableListWidget = QtWidgets.QListWidget(self.layoutWidget8)
        self.tableListWidget.setObjectName("tableListWidget")
        self.horizontalLayout_14.addWidget(self.tableListWidget)
        self.listWidget = QtWidgets.QListWidget(self.layoutWidget8)
        self.listWidget.setObjectName("listWidget")
        self.horizontalLayout_14.addWidget(self.listWidget)
        self.verticalLayout_5.addLayout(self.horizontalLayout_14)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.ddTableWidget = QtWidgets.QTableWidget(self.tab_7)
        self.ddTableWidget.setGeometry(QtCore.QRect(60, 130, 1021, 531))
        self.ddTableWidget.setObjectName("ddTableWidget")
        self.ddTableWidget.setColumnCount(8)
        self.ddTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.ddTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.ddTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.ddTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.ddTableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.ddTableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.ddTableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.ddTableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.ddTableWidget.setHorizontalHeaderItem(7, item)
        self.widget1 = QtWidgets.QWidget(self.tab_7)
        self.widget1.setGeometry(QtCore.QRect(60, 50, 191, 31))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_29.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.ddRadioButton = QtWidgets.QRadioButton(self.widget1)
        self.ddRadioButton.setChecked(True)
        self.ddRadioButton.setObjectName("ddRadioButton")
        self.horizontalLayout_29.addWidget(self.ddRadioButton)
        self.radioButton_4 = QtWidgets.QRadioButton(self.widget1)
        self.radioButton_4.setObjectName("radioButton_4")
        self.horizontalLayout_29.addWidget(self.radioButton_4)
        self.tabWidget.addTab(self.tab_7, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.updateTextEdit = QtWidgets.QTextEdit(self.tab_6)
        self.updateTextEdit.setGeometry(QtCore.QRect(60, 60, 1021, 581))
        self.updateTextEdit.setObjectName("updateTextEdit")
        self.tabWidget.addTab(self.tab_6, "")
        self.layoutWidget9 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget9.setGeometry(QtCore.QRect(30, 10, 691, 31))
        self.layoutWidget9.setObjectName("layoutWidget9")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget9)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.layoutWidget9)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget9)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_4.addWidget(self.comboBox)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget9)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_7.addWidget(self.label_9)
        self.ipLineEdit = QtWidgets.QLineEdit(self.layoutWidget9)
        self.ipLineEdit.setObjectName("ipLineEdit")
        self.horizontalLayout_7.addWidget(self.ipLineEdit)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget9)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_7.addWidget(self.label_10)
        self.portLineEdit = QtWidgets.QLineEdit(self.layoutWidget9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.portLineEdit.sizePolicy().hasHeightForWidth())
        self.portLineEdit.setSizePolicy(sizePolicy)
        self.portLineEdit.setObjectName("portLineEdit")
        self.horizontalLayout_7.addWidget(self.portLineEdit)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_7)
        gmtools.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(gmtools)
        self.statusbar.setObjectName("statusbar")
        gmtools.setStatusBar(self.statusbar)

        self.retranslateUi(gmtools)
        self.tabWidget.setCurrentIndex(6)
        QtCore.QMetaObject.connectSlotsByName(gmtools)

    def retranslateUi(self, gmtools):
        _translate = QtCore.QCoreApplication.translate
        gmtools.setWindowTitle(_translate("gmtools", "gmtools"))
        self.label_3.setText(_translate("gmtools", "活动时间"))
        self.label_4.setText(_translate("gmtools", "活动基本信息"))
        item = self.msgTableWidget.verticalHeaderItem(0)
        item.setText(_translate("gmtools", "1"))
        item = self.msgTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("gmtools", "Heading"))
        item = self.msgTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("gmtools", "kind"))
        item = self.msgTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("gmtools", "TipsType"))
        item = self.msgTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("gmtools", "DetailType"))
        item = self.msgTableWidget.horizontalHeaderItem(4)
        item.setText(_translate("gmtools", "MainPicture"))
        item = self.msg_TableWidget.verticalHeaderItem(0)
        item.setText(_translate("gmtools", "1"))
        item = self.msg_TableWidget.horizontalHeaderItem(0)
        item.setText(_translate("gmtools", "TimeShow"))
        item = self.msg_TableWidget.horizontalHeaderItem(1)
        item.setText(_translate("gmtools", "RuleShow"))
        item = self.msg_TableWidget.horizontalHeaderItem(2)
        item.setText(_translate("gmtools", "DetailRuleShow"))
        item = self.msg_TableWidget.horizontalHeaderItem(3)
        item.setText(_translate("gmtools", "JumpAddress"))
        self.label_2.setText(_translate("gmtools", "活动关键字"))
        self.headingRadioButton.setText(_translate("gmtools", "Heading"))
        self.commentRadioButton.setText(_translate("gmtools", "ActivityID"))
        item = self.mallTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("gmtools", "ID"))
        item = self.mallTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("gmtools", "ItemList"))
        item = self.mallTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("gmtools", "ItemNum"))
        item = self.mallTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("gmtools", "MoneyType"))
        item = self.mallTableWidget.horizontalHeaderItem(4)
        item.setText(_translate("gmtools", "Price"))
        item = self.mallTableWidget.horizontalHeaderItem(5)
        item.setText(_translate("gmtools", "打折价"))
        item = self.mallTableWidget.horizontalHeaderItem(6)
        item.setText(_translate("gmtools", "Refresh"))
        item = self.mallTableWidget.horizontalHeaderItem(7)
        item.setText(_translate("gmtools", "BeginDate"))
        item = self.mallTableWidget.horizontalHeaderItem(8)
        item.setText(_translate("gmtools", "EndDate"))
        item = self.rewardTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("gmtools", "Comment"))
        item = self.rewardTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("gmtools", "state"))
        item = self.rewardTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("gmtools", "ExtraCond"))
        item = self.rewardTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("gmtools", "Reward"))
        item = self.rewardTableWidget.horizontalHeaderItem(4)
        item.setText(_translate("gmtools", "TaskTarget"))
        self.label_5.setText(_translate("gmtools", "活动奖励 "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("gmtools", "活动查询"))
        item = self.goods_TableWidget.horizontalHeaderItem(0)
        item.setText(_translate("gmtools", "DropGroup"))
        item = self.goods_TableWidget.horizontalHeaderItem(1)
        item.setText(_translate("gmtools", "ItemID"))
        item = self.goods_TableWidget.horizontalHeaderItem(2)
        item.setText(_translate("gmtools", "ItemCount"))
        item = self.goods_TableWidget.horizontalHeaderItem(3)
        item.setText(_translate("gmtools", "AnnouncementId"))
        item = self.goods_TableWidget.horizontalHeaderItem(4)
        item.setText(_translate("gmtools", "Lifetime"))
        item.setToolTip(_translate("gmtools", "单位（小时）"))
        item = self.goods_TableWidget.horizontalHeaderItem(5)
        item.setText(_translate("gmtools", "ItemWeight"))
        item = self.goods_TableWidget.horizontalHeaderItem(6)
        item.setText(_translate("gmtools", "百分比"))
        item = self.goodsTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("gmtools", "奖励道具"))
        item = self.goodsTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("gmtools", "选择数量"))
        item = self.annTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("gmtools", "ID"))
        item = self.annTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("gmtools", "ScrollContent"))
        item = self.annTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("gmtools", "WorldContent"))
        self.label_6.setText(_translate("gmtools", "宝箱内容"))
        self.label_15.setText(_translate("gmtools", "跑马灯"))
        self.goodsRadioButton.setText(_translate("gmtools", "关键字"))
        self.radioButton_3.setText(_translate("gmtools", "ID"))
        self.dropRadioButton.setText(_translate("gmtools", "DropID"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("gmtools", "宝箱查询"))
        self.label_16.setText(_translate("gmtools", "类型："))
        self.radioButton.setText(_translate("gmtools", "列表内人员邮件"))
        self.allserverRadioButton.setText(_translate("gmtools", "全服邮件"))
        self.pushButton.setText(_translate("gmtools", "发送邮件"))
        self.label_18.setText(_translate("gmtools", "主题 ："))
        self.titleLineEdit.setText(_translate("gmtools", "测试邮件"))
        self.label_19.setText(_translate("gmtools", "正文 ："))
        self.commentLineEdit.setText(_translate("gmtools", "测试正文"))
        self.label_20.setText(_translate("gmtools", "附件 ："))
        self.itemlistLineEdit.setToolTip(_translate("gmtools", "最多6个附件"))
        self.itemlistLineEdit.setText(_translate("gmtools", "112000002,1000|112000002,2000"))
        self.label_21.setText(_translate("gmtools", "过期时间(s):"))
        self.dayLineEdit.setText(_translate("gmtools", "10"))
        self.label_22.setText(_translate("gmtools", "天"))
        self.secondLineEdit.setText(_translate("gmtools", "0"))
        self.label_23.setText(_translate("gmtools", "秒"))
        self.label_13.setText(_translate("gmtools", "其他GM命令"))
        self.executePushButton.setText(_translate("gmtools", "执行"))
        self.label_25.setText(_translate("gmtools", "自定义命令"))
        self.selfPushButton.setText(_translate("gmtools", "执行"))
        self.textEdit_2.setHtml(_translate("gmtools", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.SF NS Text\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">1、输入 昵称或者物品关键字之后，键盘键入‘enter\'执行查询</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">2、选中物品列表中的物品会自动在GM中添加此物品ID</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">3、双击列表中的选定项删除选定项</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">4、GM命令执行时会对列表内所有玩家都有效，也会发送物品列表中的所有物品</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">5、发送邮件如果不是全服邮件，则会发送给玩家列表昵称中的所有玩家</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">6、GM自定义命令需要在配置文件中配置才有效，同样对列表内所有玩家有效</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">7、邮件最多6个附件</span></p></body></html>"))
        self.label_8.setText(_translate("gmtools", "玩家昵称"))
        self.label_24.setText(_translate("gmtools", "玩家昵称列表"))
        self.clearPushButton.setText(_translate("gmtools", "清空列表"))
        self.nameRadioButton.setText(_translate("gmtools", "关键字"))
        self.idRadioButton.setText(_translate("gmtools", "ID"))
        self.label_26.setText(_translate("gmtools", "物品列表"))
        self.clearPushButton_2.setText(_translate("gmtools", "清空列表"))
        self.label_12.setText(_translate("gmtools", "数量"))
        self.sendPushButton.setText(_translate("gmtools", "发送"))
        self.addmailPushButton.setText(_translate("gmtools", "添加到邮件附件"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("gmtools", "GM命令"))
        self.label_17.setText(_translate("gmtools", "选择模板"))
        self.tsRadioButton.setText(_translate("gmtools", "模板表"))
        self.tuRadioButton.setText(_translate("gmtools", "用户表"))
        self.sqlPushButton.setText(_translate("gmtools", "执行"))
        self.label_11.setText(_translate("gmtools", "执行结果"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("gmtools", "改表查询"))
        self.label_7.setText(_translate("gmtools", "模板表名关键字"))
        self.label_14.setText(_translate("gmtools", "用户表名关键字"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("gmtools", "表名查询"))
        item = self.ddTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("gmtools", "ShowReward"))
        item.setToolTip(_translate("gmtools", "客户端展示奖励"))
        item = self.ddTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("gmtools", "Location"))
        item = self.ddTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("gmtools", "IsRare"))
        item.setToolTip(_translate("gmtools", "<html><head/><body><p>是否稀有</p><p>稀有 1</p><p>普通 0</p></body></html>"))
        item = self.ddTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("gmtools", "DropId"))
        item = self.ddTableWidget.horizontalHeaderItem(4)
        item.setText(_translate("gmtools", "等级下限"))
        item = self.ddTableWidget.horizontalHeaderItem(5)
        item.setText(_translate("gmtools", "等级上限"))
        item = self.ddTableWidget.horizontalHeaderItem(6)
        item.setText(_translate("gmtools", "抽取概率"))
        item = self.ddTableWidget.horizontalHeaderItem(7)
        item.setText(_translate("gmtools", "RewardCoin"))
        item.setToolTip(_translate("gmtools", "<html><head/><body><p>每次抽取获得代币数量</p></body></html>"))
        self.ddRadioButton.setText(_translate("gmtools", "欧皇觅宝"))
        self.radioButton_4.setText(_translate("gmtools", "幸运广场"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("gmtools", "弹弹宝藏"))
        self.updateTextEdit.setHtml(_translate("gmtools", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.SF NS Text\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2018-08-25</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1、新增弹弹宝藏查询功能</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2、宝箱查询中新增DropId查询功能</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">3、t_s_rewardmissionitem表查询itemname字段修改为itemid</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">4、宝箱查询中新增TaskTarget字段，用于翻译cond为1000的活动任务条件</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("gmtools", "更新公告"))
        self.label.setText(_translate("gmtools", "数据库"))
        self.label_9.setText(_translate("gmtools", "服务器IP"))
        self.label_10.setText(_translate("gmtools", "PORT"))
        # 设置列宽
        self.msgTableWidget.setColumnWidth(0, 300)
        self.msgTableWidget.setColumnWidth(4, 470)
        self.msg_TableWidget.setColumnWidth(3, 300)
        self.rewardTableWidget.setColumnWidth(2, 150)
        self.rewardTableWidget.setColumnWidth(3, 220)
        self.rewardTableWidget.setColumnWidth(4, 250)
        self.goods_TableWidget.setColumnWidth(0, 100)
        self.goods_TableWidget.setColumnWidth(2, 100)
        self.goods_TableWidget.setColumnWidth(3, 100)
        self.goods_TableWidget.setColumnWidth(4, 106)
        self.annTableWidget.setColumnWidth(0, 100)
        self.annTableWidget.setColumnWidth(1, 450)
        self.annTableWidget.setColumnWidth(2, 459)
        self.mallTableWidget.setColumnWidth(4, 50)
        self.mallTableWidget.setColumnWidth(5, 50)
        self.mallTableWidget.setColumnWidth(6, 50)
        self.mallTableWidget.setColumnWidth(7, 214)
        self.mallTableWidget.setColumnWidth(8, 237)
        self.mallTableWidget.setVisible(False)
        self.goodsTableWidget.setVisible(False)
        self.ddTableWidget.setColumnWidth(0, 200)
        self.ddTableWidget.setColumnWidth(7, 225)
