# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'activity.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 900)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(30, 60, 1141, 761))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.nameListWidget = QtWidgets.QListWidget(self.tab)
        self.nameListWidget.setGeometry(QtCore.QRect(50, 90, 431, 91))
        self.nameListWidget.setObjectName("nameListWidget")
        self.widget = QtWidgets.QWidget(self.tab)
        self.widget.setGeometry(QtCore.QRect(50, 490, 1021, 161))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.rewardTableWidget = QtWidgets.QTableWidget(self.widget)
        self.rewardTableWidget.setObjectName("rewardTableWidget")
        self.rewardTableWidget.setColumnCount(4)
        self.rewardTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.rewardTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.rewardTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.rewardTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.rewardTableWidget.setHorizontalHeaderItem(3, item)
        self.rewardTableWidget.horizontalHeader().setDefaultSectionSize(200)
        self.verticalLayout.addWidget(self.rewardTableWidget)
        self.widget1 = QtWidgets.QWidget(self.tab)
        self.widget1.setGeometry(QtCore.QRect(50, 30, 331, 33))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.widget1)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.nameLineEdit = QtWidgets.QLineEdit(self.widget1)
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.horizontalLayout.addWidget(self.nameLineEdit)
        self.widget2 = QtWidgets.QWidget(self.tab)
        self.widget2.setGeometry(QtCore.QRect(50, 200, 431, 61))
        self.widget2.setObjectName("widget2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.widget2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.timeLineEdit = QtWidgets.QLineEdit(self.widget2)
        self.timeLineEdit.setObjectName("timeLineEdit")
        self.horizontalLayout_2.addWidget(self.timeLineEdit)
        self.widget3 = QtWidgets.QWidget(self.tab)
        self.widget3.setGeometry(QtCore.QRect(50, 280, 1021, 181))
        self.widget3.setObjectName("widget3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.widget3)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.msgTableWidget = QtWidgets.QTableWidget(self.widget3)
        self.msgTableWidget.setObjectName("msgTableWidget")
        self.msgTableWidget.setColumnCount(5)
        self.msgTableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.msgTableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.msgTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.msgTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.msgTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.msgTableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.msgTableWidget.setHorizontalHeaderItem(4, item)
        self.msgTableWidget.horizontalHeader().setDefaultSectionSize(80)
        self.verticalLayout_2.addWidget(self.msgTableWidget)
        self.msg_TableWidget = QtWidgets.QTableWidget(self.widget3)
        self.msg_TableWidget.setObjectName("msg_TableWidget")
        self.msg_TableWidget.setColumnCount(4)
        self.msg_TableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.msg_TableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.msg_TableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.msg_TableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.msg_TableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.msg_TableWidget.setHorizontalHeaderItem(3, item)
        self.msg_TableWidget.horizontalHeader().setDefaultSectionSize(250)
        self.verticalLayout_2.addWidget(self.msg_TableWidget)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.goodsListWidget = QtWidgets.QListWidget(self.tab_2)
        self.goodsListWidget.setGeometry(QtCore.QRect(60, 100, 411, 111))
        self.goodsListWidget.setObjectName("goodsListWidget")
        self.goods_TableWidget = QtWidgets.QTableWidget(self.tab_2)
        self.goods_TableWidget.setGeometry(QtCore.QRect(60, 260, 1011, 161))
        self.goods_TableWidget.setObjectName("goods_TableWidget")
        self.goods_TableWidget.setColumnCount(5)
        self.goods_TableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.goods_TableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.goods_TableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.goods_TableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.goods_TableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.goods_TableWidget.setHorizontalHeaderItem(4, item)
        self.goods_TableWidget.horizontalHeader().setDefaultSectionSize(200)
        self.goodsTableWidget = QtWidgets.QTableWidget(self.tab_2)
        self.goodsTableWidget.setGeometry(QtCore.QRect(510, 100, 521, 111))
        self.goodsTableWidget.setObjectName("goodsTableWidget")
        self.goodsTableWidget.setColumnCount(2)
        self.goodsTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.goodsTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.goodsTableWidget.setHorizontalHeaderItem(1, item)
        self.goodsTableWidget.horizontalHeader().setDefaultSectionSize(300)
        self.widget4 = QtWidgets.QWidget(self.tab_2)
        self.widget4.setGeometry(QtCore.QRect(60, 40, 331, 31))
        self.widget4.setObjectName("widget4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget4)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.widget4)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.goodsLineEdit = QtWidgets.QLineEdit(self.widget4)
        self.goodsLineEdit.setObjectName("goodsLineEdit")
        self.horizontalLayout_3.addWidget(self.goodsLineEdit)
        self.widget5 = QtWidgets.QWidget(self.tab_2)
        self.widget5.setGeometry(QtCore.QRect(131, 471, 841, 229))
        self.widget5.setObjectName("widget5")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.widget5)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_8 = QtWidgets.QLabel(self.widget5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_5.addWidget(self.label_8)
        self.nickLineEdit = QtWidgets.QLineEdit(self.widget5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nickLineEdit.sizePolicy().hasHeightForWidth())
        self.nickLineEdit.setSizePolicy(sizePolicy)
        self.nickLineEdit.setObjectName("nickLineEdit")
        self.horizontalLayout_5.addWidget(self.nickLineEdit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.nickListWidget = QtWidgets.QListWidget(self.widget5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nickListWidget.sizePolicy().hasHeightForWidth())
        self.nickListWidget.setSizePolicy(sizePolicy)
        self.nickListWidget.setObjectName("nickListWidget")
        self.verticalLayout_3.addWidget(self.nickListWidget)
        self.horizontalLayout_10.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_11 = QtWidgets.QLabel(self.widget5)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_6.addWidget(self.label_11)
        self.itemidLineEdit = QtWidgets.QLineEdit(self.widget5)
        self.itemidLineEdit.setObjectName("itemidLineEdit")
        self.horizontalLayout_6.addWidget(self.itemidLineEdit)
        self.label_12 = QtWidgets.QLabel(self.widget5)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_6.addWidget(self.label_12)
        self.countLineEdit = QtWidgets.QLineEdit(self.widget5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.countLineEdit.sizePolicy().hasHeightForWidth())
        self.countLineEdit.setSizePolicy(sizePolicy)
        self.countLineEdit.setObjectName("countLineEdit")
        self.horizontalLayout_6.addWidget(self.countLineEdit)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_6)
        self.sendPushButton = QtWidgets.QPushButton(self.widget5)
        self.sendPushButton.setObjectName("sendPushButton")
        self.horizontalLayout_8.addWidget(self.sendPushButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_13 = QtWidgets.QLabel(self.widget5)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_9.addWidget(self.label_13)
        self.otherLineEdit = QtWidgets.QLineEdit(self.widget5)
        self.otherLineEdit.setObjectName("otherLineEdit")
        self.horizontalLayout_9.addWidget(self.otherLineEdit)
        self.executePushButton = QtWidgets.QPushButton(self.widget5)
        self.executePushButton.setObjectName("executePushButton")
        self.horizontalLayout_9.addWidget(self.executePushButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10.addLayout(self.verticalLayout_4)
        self.tabWidget.addTab(self.tab_2, "")
        self.widget6 = QtWidgets.QWidget(self.centralwidget)
        self.widget6.setGeometry(QtCore.QRect(30, 10, 691, 31))
        self.widget6.setObjectName("widget6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget6)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.widget6)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.comboBox = QtWidgets.QComboBox(self.widget6)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_4.addWidget(self.comboBox)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_9 = QtWidgets.QLabel(self.widget6)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_7.addWidget(self.label_9)
        self.ipLineEdit = QtWidgets.QLineEdit(self.widget6)
        self.ipLineEdit.setObjectName("ipLineEdit")
        self.horizontalLayout_7.addWidget(self.ipLineEdit)
        self.label_10 = QtWidgets.QLabel(self.widget6)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_7.addWidget(self.label_10)
        self.portLineEdit = QtWidgets.QLineEdit(self.widget6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.portLineEdit.sizePolicy().hasHeightForWidth())
        self.portLineEdit.setSizePolicy(sizePolicy)
        self.portLineEdit.setObjectName("portLineEdit")
        self.horizontalLayout_7.addWidget(self.portLineEdit)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_7)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_5.setText(_translate("MainWindow", "活动奖励 "))
        item = self.rewardTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Comment"))
        item = self.rewardTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "state"))
        item = self.rewardTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "ExtraCond"))
        item = self.rewardTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Reward"))
        self.label_2.setText(_translate("MainWindow", "活动关键字"))
        self.label_3.setText(_translate("MainWindow", "活动时间"))
        self.label_4.setText(_translate("MainWindow", "活动基本信息"))
        item = self.msgTableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.msgTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Heading"))
        item = self.msgTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "kind"))
        item = self.msgTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "TipsType"))
        item = self.msgTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "DetailType"))
        item = self.msgTableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "MainPicture"))
        item = self.msg_TableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.msg_TableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "TimeShow"))
        item = self.msg_TableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "RuleShow"))
        item = self.msg_TableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "DetailRuleShow"))
        item = self.msg_TableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "JumpAddress"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "活动查询"))
        item = self.goods_TableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "DropGroup"))
        item = self.goods_TableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "ItemName"))
        item = self.goods_TableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "ItemCount"))
        item = self.goods_TableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "ItemWeight"))
        item = self.goods_TableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "百分比"))
        item = self.goodsTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "奖励道具"))
        item = self.goodsTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "选择数量"))
        self.label_6.setText(_translate("MainWindow", "物品关键字"))
        self.label_8.setText(_translate("MainWindow", "玩家昵称"))
        self.label_11.setText(_translate("MainWindow", "物品ID"))
        self.label_12.setText(_translate("MainWindow", "数量"))
        self.sendPushButton.setText(_translate("MainWindow", "发送"))
        self.label_13.setText(_translate("MainWindow", "其他GM命令"))
        self.otherLineEdit.setToolTip(_translate("MainWindow", "<html><head/><body><p>GM desc=&quot;设置公会捐献贡献度(会同时设置个人的和公会的，慎用):addDonate 数量&quot;&gt;addDonate 10&lt;/GM&gt;</p><p>        &lt;GM desc=&quot;增加效果:addExpEffect 效果ID&quot;&gt;addExpEffect 104000001&lt;/GM&gt;</p><p>        &lt;GM desc=&quot;增加PVP胜利次数:addWinTimes 数量&quot;&gt;addWinTimes 10&lt;/GM&gt;</p><p>        &lt;GM desc=&quot;封号:ban 时间(s) 描述&quot;&gt;ban 10 长得太帅&lt;/GM&gt;</p><p>        &lt;GM desc=&quot;增加活力:hl 数量&quot;&gt;hl 10&lt;/GM&gt;</p><p>        &lt;GM desc=&quot;设置竞技场积分:jjc 积分&quot;&gt;jjc 100&lt;/GM&gt;</p><p>        &lt;GM desc=&quot;杀死图中的所有敌人:kill&quot;&gt;kill&lt;/GM&gt;</p><p>        &lt;GM desc=&quot;增加宝珠碎片:orb 数量&quot;&gt;orb 10&lt;/GM&gt;</p><p>        &lt;GM desc=&quot;获取宝珠:orbGet 类型(1:高级抽宝珠;2:高级五连抽)&quot;&gt;orbGet 2&lt;/GM&gt;</p><p>        &lt;GM desc=&quot;设置排位积分:pw 积分&quot;&gt;pw&lt;/GM&gt;</p><p>        &lt;GM desc=&quot;重置多人副本每日挑战次数:refb&quot;&gt;refb&lt;/GM&gt;</p><p>        &lt;GM desc=&quot;消耗物品(不一定生效):removeitem 物品ID 数量&quot;&gt;removeitem&lt;/GM&gt;</p><p>        &lt;GM desc=&quot;重置活跃度:retask&quot;&gt;retask&lt;/GM&gt;</p><p>        &lt;GM desc=&quot;设置任务信息(使用方法未知):setTask taskID XX XX XX····&quot;&gt;setTask&lt;/GM&gt;</p><p>        &lt;GM desc=&quot;设置新手节点:skip 节点(跳过新手是99999990)&quot;&gt;skip 99999990&lt;/GM&gt;</p><p>        &lt;GM desc=&quot;增加周活跃度:week 数量&quot;&gt;week&lt;/GM&gt;</p><p>        &lt;GM desc=&quot;查询竞技场积分:winpoint&quot;&gt;winpoint 90&lt;/GM&gt;</p><p>        &lt;GM desc=&quot;设置单个任务完成:updateTask 类型 任务ID&quot;&gt;updateTask 1 150050201&lt;/GM&gt;</p><p>        &lt;GM desc=&quot;重置当前的公会活动数据，完成状态全部清零:resetGuildTask&quot;&gt;resetGuildTask&lt;/GM&gt;</p><p>        &lt;GM desc=&quot;完成全部日常任务:dailyTaskFinsh&quot;&gt;dailyTaskFinsh&lt;/GM&gt;</p><p>        &lt;GM desc=&quot;主线和支线任务完成:taskFinsh 任务类型(1主线，2支线)&quot;&gt;taskFinsh 1&lt;/GM&gt;</p></body></html>"))
        self.executePushButton.setText(_translate("MainWindow", "执行"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "宝箱查询"))
        self.label.setText(_translate("MainWindow", "数据库"))
        self.label_9.setText(_translate("MainWindow", "服务器IP"))
        self.label_10.setText(_translate("MainWindow", "PORT"))
        # 设置列宽
        self.msgTableWidget.setColumnWidth(0, 300)
        self.msgTableWidget.setColumnWidth(4, 470)
        self.msg_TableWidget.setColumnWidth(3, 300)
        self.rewardTableWidget.setColumnWidth(3, 420)
